### ISSUE TITLE
How can I implement then in different dataset?

### ISSUE THREAD

**Issue by SalemAmeen** [j-wang/BanditEmpirical#1]
Sorry this is not an issue but I would like to ask you some technical implementation  regarding to implement those technique.
If I use this code in other application where can I make the change of the code? shall I change the arms or the police or keep them and change somewhere else.

Please I waiting for your advice.

**Comment by j-wang** [comment]
Hi Salem. No problem. It's been a while, but I'd suggest putting the matrix form that the bandit algorithms expect. 

If this is not possible, the get_arm and pull_arm methods in the Policy classes would be the place you'd want to do it if you're feeding in a custom data format that can't easily be put in that form. However, a lot of reusable part of the code is the math in each of those methods.

**Comment by SalemAmeen** [comment]
Many thanks,
