### ISSUE TITLE
[iss2] run_process outputs empty SQLite File

### ISSUE THREAD

**Issue by fantaandcrackers** [j-wang/BanditEmpirical#3]
When run with Yahoo dataset on files ydata-fp-td-clicks-v1_0.20090501.gz through ydata-fp-td-clicks-v1_0.20090510.gz, outputted "full.db" is an empty SQLite file.

**Comment by j-wang** [comment]
Thanks for trying it out. This is from a while ago in my grad program, so I don't have any ideas off the top of my head what that might be. I'll see if I can test it out in a few days.

**Comment by fantaandcrackers** [comment]
Hey James. Thank you. I believe this is actually an edge case that may not be especially relevant as our most recent runs of your code have been successful. Will take a deeper look in the next few days to add more details.

**Comment by j-wang** [comment]
Oh, good to hear. Keep me posted then!

**Comment by fantaandcrackers** [comment]
This issue was mistakenly created in correspondance to the line skips located at https://github.com/j-wang/BanditEmpirical/blob/master/run_process.py#L14.

I was curious, was there a reason why you chose to skip all the lines of the first day (ydata-fp-td-clicks-v1_0.20090501.gz)?
